name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  merge_group:
    types:
      - checks_requested

jobs:
  build-3rdparty:
    uses: ./.github/workflows/build-3rdparty.yml

  build-library:
    needs: build-3rdparty
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Download 3rdparty artifacts
        uses: actions/download-artifact@v4
        with:
          name: 3rdparty-output
          path: 3rdparty/output

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build package
        run: yarn prepare
