on:
  workflow_call:

jobs:
  common-steps:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Cache 3rdparty output
        id: cache-3rdparty-output
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: 3rdparty/output
          key: ${{ runner.os }}-3rdparty-output-${{ hashFiles('3rdparty/*.sh') }}
          restore-keys: |
            ${{ runner.os }}-3rdparty-output-

      - name: Install JDK
        if: steps.cache-3rdparty-output.outputs.cache-hit != 'true'
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Finalize Android SDK
        if: steps.cache-3rdparty-output.outputs.cache-hit != 'true'
        run: |
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "ndk;27.1.12297006"

      - name: Select Xcode 16.4
        if: steps.cache-3rdparty-output.outputs.cache-hit != 'true'
        run: sudo xcode-select -s "/Applications/Xcode_16.4.app/Contents/Developer"

      - name: Install dependencies
        if: steps.cache-3rdparty-output.outputs.cache-hit != 'true'
        run: |
          brew install cmake pkg-config python3 git

      - name: Build 3rdparty
        if: steps.cache-3rdparty-output.outputs.cache-hit != 'true'
        run: |
          cd 3rdparty
          ./download.sh
          ./build_ios.sh
          ./build_android.sh

      - name: Upload 3rdparty artifacts
        uses: actions/upload-artifact@v4
        with:
          name: 3rdparty-output
          path: 3rdparty/output
          retention-days: 1
